# Project specific config

#http://lint.travis-ci.org/

os:
  - linux

dist: bionic

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot

language:
  - python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta

install:
  - python3 -m pip install flake8
  - python3 -m pip install mypy typed-ast
  - python3 -m pip install pydocstyle
  - python3 -m pip install pylint

branches:
  only:
    - master

git:
  depth: 10

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change
