name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Wait for ci to succeed
      #   uses: lewagon/wait-on-check-action@v1.0.0
      #   with:
      #     ref: ${{ github.ref }}
      #     check-name: 'Build'
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag-version
        run: echo ::set-output name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Get package version
        id: package-version
        uses: codota/npm-get-version-action@master
      - name: Tag & Package.json Versions Not Matching
        if: ${{ format('v{0}', steps.package-version.outputs.current-version) != steps.tag-version.outputs.RELEASE_VERSION}}
        run: exit 1
      - uses: codota/action-setup-atom@v1
        with:
          channel: stable
      - run: apm publish -t ${{ format('v{0}', steps.package-version.outputs.current-version) }}
        env:
          ATOM_ACCESS_TOKEN: ${{secrets.ATOM_ACCESS_TOKEN}}